### ISSUE TITLE
Bug ?

### ISSUE THREAD

**Issue by theinze** [joha2/pyrate#11]
I've tried to run `demo_effl.py` and `demo_loadsave.py` but get the following error:

``` python
Traceback (most recent call last):
  File "demo_effl.py", line 69, in <module>
    s = OpticalSystem(objectDistance = 0.0)
TypeError: __init__() got an unexpected keyword argument 'objectDistance'
```

I have an Ubuntu machine, with Python 2.7.6, numpy 1.8.2, scipy 0.13.3, matplotlib 1.3.1 running ...

**Comment by joha2** [comment]
fixed
