### ISSUE TITLE
how to access core modules without using symlinks?

### ISSUE THREAD

**Issue by joha2** [joha2/pyrate#6]
PEP8 says it is highly discouraged to use relative paths for module import. the solution i use is to ln -s the pyrate core files to PyrateWorkbench directory. is there any better solution?

**Comment by joha2** [comment]
we got rid of the symlinks and the relative imports since the gui is initiated from the main directory and is invoking a subdirectory

**Comment by theinze** [comment]
```
$ python -m foobar.py
```
 :-)

**Comment by joha2** [comment]
sag mal, langweilst du dich? :D
